# Inleiding {#inleiding}

De Amerikaanse rivierkreeften komen oorspronkelijk niet in Nederland voor: ze zijn hier ontsnapt of vrijgelaten. Sinds een aantal jaar worden de kreeften op steeds meer plekken gezien. De Amerikaanse rivierkreeften hebben een negatieve invloed op het watersysteem. Ze graven in de oevers waardoor oevers afkalven en er meer bagger in de watergangen ontstaat. Ook zijn de kreeften echte alleseters: veel planten en dieren die van nature voorkomen worden door de kreeften opgegeten. Bij het zoeken naar voedsel woelen ze ook de bodem om, wat ongunstig is voor de waterplanten die er groeien. De kreeften planten zich snel voort, waardoor de hoeveelheid kreeften in korte tijd sterk kan toenemen. Kortom, kreeften kunnen een behoorlijk probleem voor de waterkwaliteit veroorzaken.



Dit onderzoek geeft meer inzicht in de verspreiding van de rivierkreeften. Met deze informatie krijgt HHSK meer inzicht waar de rivierkreeft de waterkwaliteit negatief beïnvloedt. Mogelijk helpt het ook om te begrijpen waarom de kreeften op sommige plaatsen wel of niet voorkomen. Dat kan vervolgens weer aanknopingspunten geven om maatregelen te nemen.

Het onderzoek naar de verspreiding van rivierkreeften wordt jaarlijks uitgevoerd. Deze monitoring vindt plaats op circa 450 locaties waarvan jaarlijks een derde deel (150 locaties) wordt onderzocht.

</br>

>Er komen in Nederland verschillende soorten rivierkreeften voor. Op de <a href="https://www.eis-nederland.nl/DesktopModules/Bring2mind/DMX/Download.aspx?command=core_download&entryid=689&language=nl-NL&PortalId=4&TabId=563" target="_blank">zoekkaart</a> die door Stichting EIS-Nederland (verbonden aan NCB Naturalis) worden de meest voorkomende soorten getoond. Als je een kreeft aantreft, is het met de zoekkaart is het mogelijk om op te zoeken welke soort het is.

</br>

## Onderzoeksvragen

Het onderzoek moet antwoord geven op de volgende onderzoeksvragen:

1.	Waar in het gebied komen uitheemse kreeften voor?
2.	Welke soorten kreeften zijn dat?
3.	Komen er veel of weinig kreeften voor?
4.	Breidt de kreeftenpopulatie zich uit in dichtheid en/of areaal?


