# Discussie 

## Toestemming visrechthebbenden

Vanwege de visserijwet is het voor dit onderzoek nodig om toestemming van de visrechthebbenden te verkrijgen. Alle visrechthebbenden die hebben gereageerd gaven toestemming. Een deel van de visrechthebbenden (13%) heeft echter niet gereageerd. Het is hierdoor niet duidelijk of zij bezwaren hebben tegen het onderzoek of dat ze niet de moeite hebben genomen om te reageren.

Hoewel de bereidheid om toestemming te verlenen groot was, is het proces wel tijdrovend. Het moeten regelen van toestemming is daarmee een belangrijke hindernis voor goed kreeftenonderzoek. Het kost veel tijd en het waterschap is afhankelijk van de welwillendheid van visrechthebbenden. Het zou wenselijk zijn als de wettelijke regels worden aangepast om dit onderzoek beter te faciliteren.


## Rode Amerikaanse Rivierkreeft dominant

Net als in 2020 is ook in 2021 de Rode Amerikaanse Rivierkreeft veruit het meeste aangetroffen: op de meeste locaties en in de grootste aantallen. Deze soort graaft veel in de oevers en is een echte alleseter. In tegenstelling tot de andere kreeftensoorten verspreidt deze soort zich ook over land. Door deze eigenschappen en door de grote aantallen heeft deze soort waarschijnlijk de grootste impact op het ecosysteem. Eventuele maatregelen zullen zich dan ook vooral moeten richten op de Rode Amerikaanse Rivierkreeft.

## Minder kreeften in Schieland

In Schieland zijn er op minder locaties kreeften aangetroffen dan in de Krimpenerwaard. Op de locaties in Schieland was het aantal kreeften per locatie ook kleiner. Mogelijk komt dit doordat de kreeften Schieland nog niet gekoloniseerd hebben. Het is echter ook mogelijk dat het gebied van Schieland minder geschikt is als leefgebied voor de rivierkreeften. Een mogelijke verklaring voor dit verschil is het verschil in bodemsoort: de Krimpenerwaard is een veengebied terwijl in Schieland de bodem op de meeste plaatsen uit klei bestaat. Door het kreeftenonderzoek in de komende jaren te blijven herhalen ontstaat hier na verloop van tijd meer duidelijkheid over.

## Veranderde verspreiding

De Gestreepte en Gevlekte Amerikaanse Rivierkreeft zijn dit jaar op meer locaties gevonden. De gebieden waar deze beide soorten zijn aangetroffen lijken ook te verschillen van het vorige jaar. Bij de Gestreepte Amerikaanse Rivierkreeft valt op dat de verspreiding zich dit jaar duidelijk concentreert rond de Hollandse IJssel. 

Het verspreidingspatroon van de Gestreepte en Gevlekte Amerikaanse Rivierkreeft lijkt in 2021 anders te zijn.  Mogelijk wijst de verandering op een toename van deze soorten. Het aantal locaties waar deze soorten gevonden zijn is echter klein. Het andere beeld kan daarom ook het gevolg van toeval zijn en niet wijzen op een echte verandering. Om hier meer duidelijkheid over te krijgen is het belangrijk om de monitoring voor te zetten.


