# Conclusie

Er zijn in 2021 drie verschillende soorten uitheemse kreeften gevonden, waarvan de Rode Amerikaanse Rivierkreeft het meest talrijk is. Het is duidelijk dat de kreeften in de hele Krimpenerwaard voorkomen. In Schieland komen ze op een kwart van de locaties voor. De meeste kreeften zijn in het midden van de Krimpenerwaard gevonden. In Schieland zijn de kreeften voornamelijk langs de rand aangetroffen en in kleinere aantallen. De vraag of de kreeftenpopulatie zich uitbreid in dichtheid en/of areaal kan pas worden beantwoord als het onderzoek meerdere jaren is uitgevoerd.

De verspreiding van de Rode Amerikaanse Rivierkreeft is in 2021 ongeveer hetzelfde als in 2020. De Verspreiding van de Gestreepte en de Gevlekte Amerikaanse Rivierkreeft lijkt wel enigszins veranderd te zijn. Deze soorten zijn op iets meer locaties aangetroffen en ze zijn ook op andere plaatsen gevonden.

Het is duidelijk dat de kreeften op veel plaatsen voorkomen. De aanwezigheid van kreeften is iets om rekening mee te houden. De komende jaren zullen wij het onderzoek blijven herhalen. Hiermee kunnen wij de verspreiding van de kreeften in ons gebied volgen. De kennis over de aanwezigheid van kreeften kan gebruikt worden om rekening mee te houden in ons beleid en onze werkzaamheden.
